### ISSUE TITLE
Version for 4.8.0, 4.8.1, 4.8.2

### ISSUE THREAD

**Issue by philwareham** [gocom/textpattern-lock#3]
Hi, could you possibly update the releases to include 4.8.0, 4.8.1 and 4.8.2 Textpattern versions? Thanks very much!

**Comment by gocom** [comment]
Sorry for slow response, I've now pushed the missing version tags to the repository (4.8.0 to 4.8.8).

Hopefully the installer itself still works, I haven't tested or updated it after March 2019 'weekend' updates.

**Comment by philwareham** [comment]
Thanks Jukka, hope all well with you.

**Comment by gocom** [comment]
I now had the time to test [textpattern/installer] with up-to-date Textpattern, PHP and Composer versions. It had some issues, but I was able to sort those out, and the new v1.0.11 supports 4.8.x, PHP 8.1 and Composer 2.

**Comment by philwareham** [comment]
Brilliant, thanks Jukka, I'll try this out when I next do a Textpattern deploy.
